[package]
name = "sbom-model"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
serde = { workspace = true }
indexmap = { workspace = true }
thiserror = { workspace = true }
packageurl = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }